services:
  database:
    container_name: payment-provider-db
    image: postgres:latest
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=payment-provider-db